on:
  workflow_call:
    inputs:
      browser:
        required: true
        type: string

jobs:
  admin:
    name: ${{ inputs.browser }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./www/admin

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: ".nvmrc"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        id: pnpm-install
        with:
          run_install: false

      - name: Setup pnpm cache
        uses: actions/cache@v4.0.2
        with:
          path: ${{ github.workspace }}/.pnpm-store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Setup Playwright
        run: pnpm playwright install ${{ inputs.browser }} --with-deps

      - name: Setup postgres
        run: |
          cp .env.test .env
          docker compose up postgres -d
          sleep 5
          pnpm db:push

      - name: Setup Next.js cache
        uses: actions/cache@v4.0.2
        with:
          # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
          path: ${{ github.workspace }}/www/admin/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('www/admin/*.[jt]s', 'www/admin/*.[jt]sx', '!www/admin/*.test.*', '!www/admin/node_modules/**', '!www/admin/.next/**') }}
          # If source files changed but packages didn't, rebuild from a prior cache
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Build admin
        run: |
          pnpm lint
          pnpm build

      - name: Run Tests
        run: CI=true pnpm e2e --project ${{ inputs.browser }}

      - name: Upload report
        uses: actions/upload-artifact@v4.3.6
        if: always()
        with:
          name: playwright-${{ inputs.browser }}-report
          path: ${{ github.workspace }}/www/admin/playwright-report/
          retention-days: 30
